name: Setup

description: setup PHP and composer

runs:
  using: 'composite'
  steps:
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@1.13.0
        with:
         php-version: ${{ env.PHP_VERSION }}
         extensions: ${{ env.PHP_EXTENSIONS }}
         key: ${{ env.CACHE_KEY }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}

      - name: Get Composer Cache Dir
        shell: bash
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT


      - name: Cache Dependencies
        uses: actions/cache@v4.2.4
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-cache-keys
